### ISSUE TITLE
Bluetooth incompatibility

### ISSUE THREAD

**Issue by nmitrak** [elecfreaks/pxt-PlanetX#21]
**Describe the bug**
First of all congratulations for all the great work you have done so far. I am an owner of a Nezha inventor kit which as you know it also requires the planetX extension in order to program the line sensor for a follow line project. I also want to operate the microbit via bluetooth commands but when i add the bluetooth extension i get a message that says that radio and pxt-PlanetX-AI are not compatible with the bluetooth extension. 
Is there a solution in using the bluetooth features of microbit along the nezha board and planetX extension without PlanetX-AI? Whenever i add the planetX extension , the PlanetX-AI is also added.

Thank you very much in advance.

**Comment by martinwork** [comment]
I think the Bluetooth extension is blocked because this extension names pxt-PlanetX-AI as a dependency, and pxt-PlanetX-AI names **radio**, which is incompatible with Bluetooth.

Extensions should not usually name **radio** or **microphone** unless they really cannot work without them.

I can't see a reason in the code why pxt-PlanetX-AI cannot work with Bluetooth.

https://github.com/elecfreaks/pxt-PlanetX/blob/30245793671fdc0980eab0c598b62f45086f177f/pxt.json#L8

https://github.com/elecfreaks/pxt-PlanetX-AI/blob/11da0b0489a0b6631e4d7ceb2f7f28502b4ceafd/pxt.json#L7

**Comment by nmitrak** [comment]
Thank you very much for your answer. Indeed this is the problem that causes the incompatibility issue but the pxt-planetX-AI extension is inserted automatically whenever you insert the pxt-planetX extension. One solution could be inserting pxt-planetX-AI extension independently so that the user could also use bluetooth extension whenever needed. However other underlying issues that only programmers are aware of,  may occur.
